### ISSUE TITLE
Update license and copyrights to Project Jupyter license and copyrights

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab-hdf5#13]
Now that this is migrated, the license and copyrights should be updated to be the standardized Project Jupyter license and copyrights.

**Comment by jasongrout** [comment]
The official wording of the license may be updated soon, pending https://github.com/jupyter/governance/pull/66

**Comment by telamonian** [comment]
done in 72506c5d194f7951dc324ab2b4192ccd0d59fe75
