### ISSUE TITLE
Display one-dimensional data vertically

### ISSUE THREAD

**Issue by aarchiba** [jupyterlab/jupyterlab-hdf5#132]
### Problem

When I open a one-dimensional array, I see a single line that I have to scroll horizontally in order to see the entries. The cells are by default too narrow to read a whole floating-point number, let alone a UTF-8-encoded string. Presenting the values vertically would allow the more familiar vertical scrolling, and leave more horizontal space for longer entries. It would also normally allow more entries to be visible at once.

### Proposed Solution

Treat a view of shape (n,) as shape (n,1), so that the built-in two-dimensional display code displays it vertically.

### Additional context

A couple of examples:

![Screenshot from 2023-02-16 19-55-01](https://user-images.githubusercontent.com/136867/219473328-7bdcd7d7-1406-4a6e-8f0a-19c2411bd0f3.png)

![Screenshot from 2023-02-16 19-55-28](https://user-images.githubusercontent.com/136867/219473329-d660e6df-d6d8-4994-b3b9-a5d0832ef08a.png)

![Screenshot from 2023-02-16 19-57-05](https://user-images.githubusercontent.com/136867/219473331-59503072-9c15-43ac-a8d2-d2c181025258.png)

I also note that if I supply the index "0" I get just the first entry, as expected, but I can no longer adjust the cell width (and it is too small to see much of the value).

It might be possible to make the indexing come out two-dimensional as one would in numpy, with `[np.newaxis, :]` or `[None, :]` but these do not work. The need for these is questionable; really I think it's simpler to just display one-dimensional arrays vertically, using the whole width of the window.

**Comment by aarchiba** [comment]
This is an example of HDFView showing a one-dimensional dataset:

![Screenshot from 2023-02-20 15-01-57](https://user-images.githubusercontent.com/136867/220141065-2f7cf465-e5b9-42ac-aefc-c122c7ec48a1.png)

**Comment by loichuder** [comment]
Makes sense. I will try to see what I can do.

**Comment by loichuder** [comment]
Fixed in 1.3.0
