### ISSUE TITLE
Update package maintainers on pypi

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab-hdf5#14]
Now that the project is migrated to Project Jupyter, the pypi maintainers should be updated to include probably at least Brian and Fernando, plus others from JupyterLab that can help with maintenance: https://pypi.org/project/jupyterlab-hdf/

**Comment by telamonian** [comment]
Done. I added:

- bgranger
- blink1073
- fperez
- jasongrout
- saulshanabrook
