### ISSUE TITLE
Document why not using h5serve 

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-hdf5#15]
I just had a call with @telamonian, Shreyas Cholia, and @JonjonHays. Jon and Shreyas are going to push forward on this extension and one question they had when looking at the code  was why it wasn't using [`h5serv`](https://github.com/HDFGroup/h5serv) and instead implementing its own backend. We could use `h5vserv` with [jupyter server proxy](https://jupyter-server-proxy.readthedocs.io/en/latest/) to expose it. However @telamonian said that he originally looked into using it, but thought it would be more performant and easier to maintain to reimplement it, if we only needed to support the read case.

It would be good to document this rationale in the README so that if others come to the project with the same question they can have it answered.

**Comment by telamonian** [comment]
Shortest story: `h5serv` is meant to expose a large slice of the functionality of one of the most complex c libs ever written (ie the base c hdf5 implementation), wheareas our backend is just trying to do exactly one thing (stream dataset slabs of arbitrary shape on demand) very well.
