### ISSUE TITLE
File not found for correct path

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab-hdf5#21]
I pasted the path that I confirmed working in a notebook into the top cell of the HDF viewer and it claims there's no file found (see screenshot).

The path is long, and the viewer shows wiggly lines in the part where there are multiple dots, is it breaking any filename rules for HDF that I'm not aware of?

The path is:

/Users/klay6683/Dropbox/data/planet4/P4_catalog_v1.0_supplementary_data/P4_catalog_v1.0_raw_classifications.hdf

<img width="1524" alt="Screenshot 2019-11-18 23 16 07" src="https://user-images.githubusercontent.com/69774/69121428-99fbbb00-0a59-11ea-9553-ab961cf965e2.png">

**Comment by telamonian** [comment]
That's an absolute path, but you need to be using a path that's relative to your jupyterlab home dir. You can easily obtain said relative path by right clicking on your `.hdf` file in the regular filebrowser and selecting "Copy Path" from the context menu that pops up.

**Comment by telamonian** [comment]
Looking at your use case here, I do think it would be nice if the hdf5 path input box could correctly interpret absolute paths. However, implementation-wise it would be an awkward fit.

Basically, all of the pathing stuff for the underlying ContentsManager is designed with the pretense that your jupyterlab home dir *is* the root dir of your filesystem. It is possible to break said abstraction, but by convention it's discouraged.

**Comment by RobertoMaurizzi** [comment]
What I'm seeing is that I have a file copied under Sat/A2015121113500.L2_LAC.NorthNorwegianSeas.hdf and I'm not even getting an error, while on the console from where I started Jupyter I see `401 GET /hdf/contents/Sat/A2015121113500.L2_LAC.NorthNorwegianSeas.hdf?uri=%2F&1579965022587 (127.0.0.1) 2.73ms referer=http://localhost:8888/lab`

My Jupyter is set up with simple password authentication. Is that the problem?

jupyterlab==1.2.6 with everything updated, Python 3.7.4

**Comment by telamonian** [comment]
@RobertoMaurizzi you need the right file ending: `.hdf5`, not `.hdf`. Closing the original issue as won't fix, since paths in the hdf5 browser are already working the same as in the main juptyerlab filebrowser.

Further discussion about the dumb file extension issues will be ongoing at #40

**Comment by bitagoras** [comment]
I can't open any file either, no matter how I try to open it. The file test.hdf5 is in the base directory of jupyter.
Some system information:
- Jupyter Lab: Version 2.2.6
- Windows 10
- Absolute Path of test file: "F:\test.hdf5"

![grafik](https://user-images.githubusercontent.com/10660123/109062701-8c1af800-76e8-11eb-9438-0aff48466047.png)

**Comment by loichuder** [comment]
@bitagoras Let's continue the discussion at #40
