### ISSUE TITLE
Show attributes

### ISSUE THREAD

**Issue by moble** [jupyterlab/jupyterlab-hdf5#28]
Thanks for this really helpful extension.

I would really appreciate a way to view attributes on groups and datasets — possibly by extending a drop-down under the relevant item.

**Comment by telamonian** [comment]
I had a good meeting today with @loichuder about this exact issue. So support for this feature might actually be coming soon!

**Comment by AntonClaesson** [comment]
Any updates on this? This feature would be very helpful!

**Comment by loichuder** [comment]
@AntonClaesson Thanks for the ping, I may find some time to implement this week or the next one.
