### ISSUE TITLE
Directory not found "hdf:" 

### ISSUE THREAD

**Issue by caviri** [jupyterlab/jupyterlab-hdf5#29]
Hello, 

I try to open some .h5 files in Jupyterlab 1.2.5 and jupyterlabhdf 0.3.0 but this error appears:

Directory not found "hdf:" 

I have jupyterhub running remotely in a linux machine. 

Thanks in advance!

**Comment by caviri** [comment]
Ok, is due to the extension. It seems is only accepting files with `.hdf5` format.

**Comment by loichuder** [comment]
In fact, I get the same error (Jupyterlab 1.2.6, jupyterlab-hdf5 0.4.0) whatever the extension of the file... Maybe the issue is not solved yet ?

**Comment by StanczakDominik** [comment]
I also have this issue in Jupyterlab 2.2.8, with jupyterlab-hdf-0.4.1. I think this one needs reopening :(

**Comment by 183amir** [comment]
I have the same issue. Could you please reopen this issue?

**Comment by Migelo** [comment]
Happened just today with `jupyterlab 3.1.18` and `jupyterlab-hdf 1.0.0`. I can't get the extension to show any files, it just shows that anytime I click on it on the side.

![image](https://user-images.githubusercontent.com/6537512/137894390-d2cf51f1-469f-4fb2-8cf0-b02e52b8ca22.png)

**Comment by loichuder** [comment]
This is usually due to the server extension not enabled/installed.

Could you see if `jupyterlab_hdf` is present and activated (`OK`) when running `jupyter serverextension list` ?

**Comment by Migelo** [comment]
- nothing happens after I import it, so I guess that means it works :)
- I installed with `pip`. On a fresh installation I tried to open a file `/u/username/pyslurm/historical.hdf5`and got  this error in the jupyterlab terminal. For some reason the leading `/` missing in the 2nd line.
```
[E 2021-10-20 10:12:14.704 ServerApp] The request specified a file that does not exist.
    relfpath: u/username/pyslurm/historical.hdf5, uri: /, min_ndim: None, ixs
[historicalbackup.zip](https://github.com/jupyterlab/jupyterlab-hdf5/files/7379388/historicalbackup.zip)
tr: None, subixstr: None, attr_keys: None
[W 2021-10-20 10:12:14.705 ServerApp] 403 GET /hdf/contents/u/username/pyslurm/historical.hdf5?uri=%2F&1634717534675 (130.183.86.36) 21.11ms referer=https://localhost:50125/lab/workspaces/auto-L
```
- a file containing the historical usage of our HPC cluster
