### ISSUE TITLE
The extension "@jupyterlab/hdf5" does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by matsujju** [jupyterlab/jupyterlab-hdf5#33]
Extension Installation Error

An error occurred installing @jupyterlab/hdf5.

Error message: The extension "@jupyterlab/hdf5" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/application
>=2.1.1 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/apputils
>=4.1.0 <4.2.0          >=3.2.0 <4.0.0 @jupyterlab/coreutils
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/docmanager
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/filebrowser
>=2.1.2 <2.2.0          >=1.2.0 <2.0.0 @jupyterlab/notebook
>=5.1.0 <5.2.0          >=4.2.0 <5.0.0 @jupyterlab/services

**Comment by smaegol** [comment]
I confirm. Any solution?

```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.2.3 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/application
>=2.2.3 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/apputils
>=4.2.2 <4.3.0          >=3.2.0 <4.0.0 @jupyterlab/coreutils
>=2.2.1 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/docmanager
>=2.2.1 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/filebrowser
>=2.2.3 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/notebook
>=5.2.2 <5.3.0          >=4.2.0 <5.0.0 @jupyterlab/services
```

**Comment by Cherrymelon** [comment]
I confirm too.
```
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.2.4 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/application
>=2.2.4 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/apputils
>=4.2.3 <4.3.0          >=3.2.0 <4.0.0 @jupyterlab/coreutils
>=2.2.2 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/docmanager
>=2.2.2 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/filebrowser
>=2.2.4 <2.3.0          >=1.2.0 <2.0.0 @jupyterlab/notebook
>=5.2.3 <5.3.0          >=4.2.0 <5.0.0 @jupyterlab/services
```
I think maybe editing dependencies requirement file can work,but I don't know how to install jupyter labextension locally

**Comment by telamonian** [comment]
The latest v0.4.0 release now includes support for juptyerlab 2.x (tested with the latest jlab v2.2.7 release).

@matsujju @smaegol @Cherrymelon Please try out the standard jupyterlab-hdf install:

```
pip install jupyterlab_hdf
jupyter labextension install @jupyterlab/hdf5
```

and let me know if you run into any further troubles in a fresh issue
