### ISSUE TITLE
unable to open file

### ISSUE THREAD

**Issue by akritikts** [jupyterlab/jupyterlab-hdf5#34]
after successful installation, the file still does not open, it keeps navigating through the groups.
dataset: redd.h5(low frequency)

**Comment by telamonian** [comment]
again, this is the same dumb `.hdf5` vs `.h5` file ending issue that keeps popping up. This is on my list of things to fix, but it will require some upstream fixes in juptyerlab's filebrowser component. I'm going to consolidate all future discussion of the issue to #40
