### ISSUE TITLE
Cells only display values if scrolled out of view once

### ISSUE THREAD

**Issue by loichuder** [jupyterlab/jupyterlab-hdf5#37]
I tried v0.4.0 https://github.com/jupyterlab/jupyterlab-hdf5/issues/30#issuecomment-691741733 and I did not get any problem to install/launch it :tada: 

However, I observed the following behaviour when opening a dataset:
-  All visible cells are empty
- If I scroll down, the cells that were hidden contain values as expected
- If I scroll back up, the previously empty cells now contain values

That can lead to strange displays (Tested on Firefox 80.0.1 and Chrome 84.0)
![image](https://user-images.githubusercontent.com/42204205/93049045-7ea11280-f660-11ea-8e97-514bc8bf79da.png)

I also get `Uncaught (in promise) TypeError: shape is undefined` in the console:
![image](https://user-images.githubusercontent.com/42204205/93049209-d6d81480-f660-11ea-8a67-11710dd0cf57.png)

but I am not sure this is related as it appears before I open the dataset.

**EDIT:** The error seems instead related to an error 403 I got above as it cannot resolve a file I previously opened. Also, changing tabs seems to also trigger the display of values.

**Comment by cnydw** [comment]
@telamonian Thanks for the new release.

Indeed, I also encountered this issue, and I was able to view the data by minimizing and maximizing the view by dragging the filebrowser back and forth.

**Comment by telamonian** [comment]
I've definitely seen similar issues before during development. However, I can't reproduce the issue locally.

@loichuder @cnydw What version of Jupyterlab are each of you running? Can you please run the following in a terminal:

```
jupyter labextension list
jupyter serverextension list
```

and post the output here in this thread?

**Comment by telamonian** [comment]
I found a bug where small datasets were rendering blank when initially shown. I fixed it and did a v0.4.1 bugfix release. @cnydw Can you please try out v0.4.1 and see if it fixes your issue?

Unfortunately, @loichuder I don't think the bug that I found is directly related to your problem, since I wasn't seeing any errors on the console. I suspect you might have a version mismatch between your jupyterlab-hdf5 labextension and serverextension, so please run those commands I posted above and post the output

**Comment by loichuder** [comment]
@telamonian v0.4.1 indeed fixes the blank datasets issue, thanks for the quick fix :clap: !

For the other error, I reproduced it on another computer with the following steps:
- Launch `jupyter lab` from a CLI in a given folder and open a HDF5 file with it.
- Quit JupyterLab and **change folder**
- Run `jupyter lab` once again in the new folder and you should see 403 in the console as it cannot resolve the relative paths anymore.

Here are the outputs of `jupyter labextension list`:
```@jupyterlab/hdf5 v0.4.1  enabled  OK```

and `jupyter serverextension list`:
```
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.8 OK
    jupyterlab_hdf  enabled 
    - Validating...
      jupyterlab_hdf 0.4.1 OK
```
Note that I installed `jupyterlab` (and the extensions) in a venv created by [pew](https://pypi.org/project/pew/). Not sure if that's relevant.

**Comment by loichuder** [comment]
I will close this since 0.4.1 fixed the issue.
