### ISSUE TITLE
Proposals to improve the backend

### ISSUE THREAD

**Issue by loichuder** [jupyterlab/jupyterlab-hdf5#53]
I have played a bit with the new endpoints and have a few improvements to propose:

### Needs discussion

- [ ] 1) As attributes can store complex data (i.e. arrays), the type and shape of attributes should be returned. #87 

<s> 2) The type of datasets is also tough to find as the `dtype` field is the NumPy type and not the HDF5 type. One could infer the HDF5 type from the `dtype`  but I would prefer that the backend provides directly the HDF5 type.</s> **Not implemented**: https://github.com/silx-kit/h5web/issues/406#issuecomment-773849966

<s> 3) Similarly, `shape` is the NumPy shape is not the shape in the HDF5 sense of the term. A HDF5 shape can be simple (as you expect it) or be a compound shape for more complex datasets. To support these, I think the HDF5 shape should be returned.</s> **Not implemented**: https://github.com/jupyterlab/jupyterlab-hdf5/issues/53#issuecomment-746123299

### Uncontroversial

- [x] **Added in #60** -> Less critical, HDF5 entities are indexed internally by an `id`. It could be an additional field returned by the `hdf/meta` endpoint. **REMOVED in #70 and #77**, see #68 for the discussion. 

@telamonian please give me your thoughts

**Comment by telamonian** [comment]
For the `id`, go for it. Definitely should be in the metadata

**Comment by telamonian** [comment]
In general, I want the backend to return numpy-like (or at least h5py-like) data. But I'm not opposed to adding alternative behavior gated behind a query parameter.

Before we discuss details though, can you please add an example `.hdf5` file (to the `/examples` dir on this repo) for each of your suggestions 1), 2) and 3) that shows off a case for which your fixes would be needed?

**Comment by telamonian** [comment]
> One could infer the HDF5 type from the `dtype`  but I would prefer that the backend provides directly the HDF5 type.

If I dig through all of my old c++ code that I wrote for my PhD, I think I had a whole bunch of conversion functions for dealing with crap like that... not that c++ code would be particularly helpful here

**Comment by loichuder** [comment]
I retract point 3: I mixed compound types and shapes together... 

The shape can actually only be scalar, simple or null.
