### ISSUE TITLE
Include sample hf5 file?

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab-hdf5#6]
It might be useful to include some sample hdf5 files, to help with development and for demo purposes.

**Comment by telamonian** [comment]
I was going to say:

> You can generate your own using the notebooks in scratch (or just the `genNested` function from `genNested.py`). I didn't include any actual `.hdf5` files cause the ones I was testing with were fairly large.

But no, you're definitely right. I'll add a couple of small-ish ones
