### ISSUE TITLE
Modernize signature of `get` method in backend

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab-hdf5#61]
I keep forgetting about this, but

https://github.com/jupyterlab/jupyterlab-hdf5/blob/8ea9fc03360a322cbac54db82222d21f0604f0b2/jupyterlab_hdf/baseHandler.py#L108-L109

needs to become

```python
    from tornado import web

    @web.authenticated
    async def get(self):
```

This will:

- update the (deprecated) tornado coroutine to the native python async support
- add https authentication to the endpoint, which is just a Good Idea

@loichuder If you're currently writing unittests for the enpoints, you'll probably want to make sure this change has been made before you get in too deep (it may subtlely change some behavior). You can just add this change to unittest PR, or I can take care of it if you prefer

**Comment by loichuder** [comment]
I am not that deep into the tests yet so you can make any changes you see fit and I will change my tests accordingly
