### ISSUE TITLE
[Discussion] Keep/remove `id` from backend response ?

### ISSUE THREAD

**Issue by loichuder** [jupyterlab/jupyterlab-hdf5#68]
After discussion with @axelboc, I have come to wonder whether `id` should be in the API responses.

- The true identifier for entities in the API is the path in the HDF5 (or `uri`). Adding an `id` which is in fact **not** the REST API identifier is confusing.
- After a few tries with hard and soft links, I realized that the same entity accessed through two different paths has a different `id`.
-  In the end, it is a number that I had to dig from the lower levels of h5py while the rest of the backend uses only the high-level layer (which is fine as it eases things a lot, especially for link resolution).
- It is a **big** integer that raises some issues: #67 

For these reasons, I struggle to find a usecase for `id` and would be in favour of removing it, favoring `uri` as the identifier.

**Comment by telamonian** [comment]
for now, i too have no use case for `id`. If it's causing any issues, let's remove `id` from the response for now, and if/when a use case develops we'll revisit including `id`
