### ISSUE TITLE
Include group links in `/hdf/meta` endpoint response

### ISSUE THREAD

**Issue by axelboc** [jupyterlab/jupyterlab-hdf5#72]
Whenever I fetch a group that contains children, I always end up calling these two endpoints in sequence:

- `/hdf/meta`, which tells me that the entity is a group and how many children it contains (`childrenCount`);
- `/hdf/contents`, which gives me some basic info about the group's children (`name`, `uri` and `type`) -- in other words, the [group's links](http://davis.lbl.gov/Manuals/HDF5-1.8.7/UG/09_Groups.html).

I can't think of a real-world use case where one would need to know that an entity is a group and that this group contains links, without actually needing to fetch those links. I fell like `/hdf/meta` should just include a `links` array in a group's response.

**Comment by telamonian** [comment]
So the way that you could do this right now with one call to `/hdf/contents` is to test if the return value is an array: if the endpoint returns an array, the entity is a group. Not the best, but it'll work

I agree that this can be improved. The current design of `/hdf/contents` is mostly to suit existing patterns in the jupyter contents stack, but we're not necessarily locked into said patterns. Probably the way to go forward will be to combine the `/hdf/meta` and `/hdf/contents` endpoints into one reasonable endpoint, and then refactor the code in `src/contents.ts` to match:

https://github.com/jupyterlab/jupyterlab-hdf5/blob/e0c804d0af07f9b5517173c7c8eebe751c0b11fb/src/contents.ts#L283-L347

**Comment by axelboc** [comment]
Yeah, the downside of checking the return type of `/hdf/contents` is that it provides no information about attributes like `/hdf/meta` does, so I end up calling either `/hdf/attrs` all the time even for entities that don't have any attributes, or `/hdf/meta` to first get `attributesCount`.

In my opinion, the perfect metadata endpoint would actually include a bit more:

- for a group: the metadata of its direct children (i.e. on one level only)
- for any entity: the metadata of the attributes (i.e. names and types, but not values)

There would then be an endpoint to fetch the value of a specific attribute (or multiple attributes for batching purposes).
